package vista;

import controlador.UsuarioController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import modelo.Usuario;

/**
 *
 * @author Edison Zambrano
 */
public class InterUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterAlumno
     */
    public static int idUsuario = 0;
    public static String cedula = "";
    public static String correo = "";

    public InterUsuario() {
        initComponents();
        this.setResizable(false);
        this.setSize(1130, 550);
        this.setTitle("Módulo de Administración de Estudiantes");

        this.cargarTablaUsuarios();
        this.CargarEstilos();
    }

    /**
     * Metodo para aplicar los estilos a la tabla
     */
    private void CargarEstilos() {
        // ESTILOS
        // Estilos del encabezado del jtable
        JTableHeader header = jTable_usuarios.getTableHeader();
        header.setFont(new Font("Serif", Font.BOLD, 18));  // Fuente negrita para el encabezado
        header.setBackground(Color.WHITE);  // Fondo del encabezado
        header.setForeground(new Color(11, 34, 97));  // Color de Texto del encabezado
        // Cambiar la fuente de la tabla
        jTable_usuarios.setFont(new Font("Serif", Font.PLAIN, 20));
        // Cambiar el color de fondo de las celdas seleccionadas
        jTable_usuarios.setSelectionBackground(new Color(0, 255, 255));
        // Cambiar el color del texto de las celdas seleccionadas
        jTable_usuarios.setSelectionForeground(new Color(30, 119, 37));
        // Cambiar el color de la cuadrícula
        jTable_usuarios.setGridColor(Color.BLACK);
        // Ajusta la altura de las filas de la tabla
        jTable_usuarios.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_nuevo_estudiante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_usuarios = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administración de Usuarios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1080, -1));

        jButton_nuevo_estudiante.setBackground(new java.awt.Color(204, 255, 255));
        jButton_nuevo_estudiante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_nuevo_estudiante.setForeground(new java.awt.Color(0, 102, 255));
        jButton_nuevo_estudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-estudiante.png"))); // NOI18N
        jButton_nuevo_estudiante.setText("NUEVO USUARIO");
        jButton_nuevo_estudiante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_nuevo_estudiante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_nuevo_estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevo_estudianteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_nuevo_estudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 100));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(480, 402));

        jTable_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_usuarios.setPreferredSize(new java.awt.Dimension(400, 80));
        jScrollPane1.setViewportView(jTable_usuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 920, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_nuevo_estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevo_estudianteActionPerformed
        // Crear una instancia del dialogo
        NuevoUsuarioDialogForm dialog = new NuevoUsuarioDialogForm((JFrame) SwingUtilities.getWindowAncestor(InterUsuario.this), true);
        // Mostrar el dialogo de forma modal
        NuevoUsuarioDialogForm.jButton_actualizar.setEnabled(false);
        NuevoUsuarioDialogForm.jButton_guardar.setEnabled(true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton_nuevo_estudianteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_nuevo_estudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_usuarios;
    // End of variables declaration//GEN-END:variables

    /*
     * *****************************************************
     * metodo para mostrar todos los usuarios registrados
     * *****************************************************
     */
    private void cargarTablaUsuarios() {

        // Crear el controlador y obtener los usuarios
        UsuarioController controller = new UsuarioController();
        ArrayList<Usuario> listaUsuarios = controller.obtenerUsuarios();

        // Crear las columnas de la tabla
        String[] columnas = {"ID", "Tipo Usuario", "Nombres", "Correo", "Clave", "Estado"};

        // Crear el modelo de la tabla y agregar los datos del ArrayList
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columnas);

        jTable_usuarios = new JTable(model);
        jScrollPane1.setViewportView(jTable_usuarios);

        // Configurar el ancho de las columnas
        jTable_usuarios.getColumnModel().getColumn(0).setPreferredWidth(40);  // ID
        jTable_usuarios.getColumnModel().getColumn(1).setPreferredWidth(300); // Tipo de Usuario
        jTable_usuarios.getColumnModel().getColumn(2).setPreferredWidth(350); // Nombres
        jTable_usuarios.getColumnModel().getColumn(3).setPreferredWidth(300); // Correo
        jTable_usuarios.getColumnModel().getColumn(4).setPreferredWidth(200); // Clave
        jTable_usuarios.getColumnModel().getColumn(5).setPreferredWidth(150); // Estado

        this.CargarEstilos();
        // Llenar el modelo con los datos del ArrayList<Usuario>
        for (Usuario usuario : listaUsuarios) {
            Object[] fila = {
                usuario.getIdUsuario(),
                usuario.getTipo_usuario().getDescripcion(),
                usuario.getNombres() + " " + usuario.getApellidos(),
                usuario.getCorreo(),
                usuario.getClave(),
                usuario.getEstado()
            };
            model.addRow(fila);
        }

        //evento para obtener campo al cual el usuario da click
        //y obtener la interfaz que mostrara la informacion general
        jTable_usuarios.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_usuarios.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idUsuario = (int) model.getValueAt(fila_point, columna_point);
                    controller.enviarDatosAModal(idUsuario);//metodo
                }
            }
        });
    }

}
