package vista;

import conexion.Conexion;
import controlador.MantenimientoController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import modelo.Mantenimiento;

/**
 *
 * @author Grupo 3 -
 */
public class InterMantenimiento extends javax.swing.JInternalFrame {

    public static int idMantenimiento = 0;
    private int idCategoria = 0;

    public InterMantenimiento() {
        initComponents();
        this.setResizable(false);
        this.setSize(1300, 550);
        this.setTitle("Módulo de Administración de Equipos en Mantenimientos");

        this.cargarTablaMantenimientos();
        this.CargarEstilos();
        this.cargarComboCategorias();

    }

    /**
     * Metodo para aplicar los estilos a la tabla
     */
    private void CargarEstilos() {
        // ESTILOS
        // Estilos del encabezado del jtable
        JTableHeader header = jTable_mantenimientos.getTableHeader();
        header.setFont(new Font("Serif", Font.BOLD, 18));  // Fuente negrita para el encabezado
        header.setBackground(Color.WHITE);  // Fondo del encabezado
        header.setForeground(new Color(11, 34, 97));  // Color de Texto del encabezado
        // Cambiar la fuente de la tabla
        jTable_mantenimientos.setFont(new Font("Serif", Font.PLAIN, 20));
        // Cambiar el color de fondo de las celdas seleccionadas
        jTable_mantenimientos.setSelectionBackground(new Color(0, 255, 255));
        // Cambiar el color del texto de las celdas seleccionadas
        jTable_mantenimientos.setSelectionForeground(new Color(30, 119, 37));
        // Cambiar el color de la cuadrícula
        jTable_mantenimientos.setGridColor(Color.BLACK);
        // Ajusta la altura de las filas de la tabla
        jTable_mantenimientos.setRowHeight(30);
        // Crear un borde para solo la parte inferior
        Border bottomBorder = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_nuevo_equipo_a_mantenimiento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_mantenimientos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_categorias = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_status = new javax.swing.JComboBox<>();
        jButton_filtrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRACIÓN DE EQUIPOS EN MANTENIMIENT0S");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1230, -1));

        jButton_nuevo_equipo_a_mantenimiento.setBackground(new java.awt.Color(204, 255, 255));
        jButton_nuevo_equipo_a_mantenimiento.setFont(new java.awt.Font("Segoe UI", 1, 5)); // NOI18N
        jButton_nuevo_equipo_a_mantenimiento.setForeground(new java.awt.Color(0, 102, 255));
        jButton_nuevo_equipo_a_mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nueva-pestana.png"))); // NOI18N
        jButton_nuevo_equipo_a_mantenimiento.setText("AGREGAR EQUIPO A MANTENIMIENTO");
        jButton_nuevo_equipo_a_mantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_nuevo_equipo_a_mantenimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_nuevo_equipo_a_mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevo_equipo_a_mantenimientoActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_nuevo_equipo_a_mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 100));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(480, 402));

        jTable_mantenimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_mantenimientos.setPreferredSize(new java.awt.Dimension(400, 80));
        jScrollPane1.setViewportView(jTable_mantenimientos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 1070, 350));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Categorias:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jComboBox_categorias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Categoria:" }));
        jPanel1.add(jComboBox_categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 250, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Estatus de los equipos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jComboBox_status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Status:", "Nuevo", "En Mantenimiento", "Operativo" }));
        jPanel1.add(jComboBox_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 250, 30));

        jButton_filtrar.setBackground(new java.awt.Color(0, 255, 204));
        jButton_filtrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_filtrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_filtrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jButton_filtrar.setText("FILTRAR");
        jButton_filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_filtrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_filtrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_nuevo_equipo_a_mantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevo_equipo_a_mantenimientoActionPerformed
        // Crear una instancia del dialogo
        NuevoMantenimientoDialogForm dialog = new NuevoMantenimientoDialogForm((JFrame) SwingUtilities.getWindowAncestor(InterMantenimiento.this), true);
        // Mostrar el dialogo de forma modal
        NuevoMantenimientoDialogForm.jButton_actualizar.setEnabled(false);
        NuevoMantenimientoDialogForm.jButton_guardar.setEnabled(true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton_nuevo_equipo_a_mantenimientoActionPerformed

    private void jButton_filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_filtrarActionPerformed

        Integer idCategoria = null;
        String status = null;

        // Categoria
//        if (jComboBox_categorias.getSelectedIndex() > 0) {
//
//            Categoria categoria
//                    = (Categoria) jComboBox_categorias.getSelectedItem();
//
//            idCategoria
//                    = categoria.getIdCategoria();
//        }
        idCategoria = obtenerIdCategoria();

        // Status
        if (jComboBox_status.getSelectedIndex() > 0) {

            status
                    = jComboBox_status
                            .getSelectedItem()
                            .toString();
        }

        MantenimientoController controller
                = new MantenimientoController();

        ArrayList<Mantenimiento> lista
                = controller.filtrarMantenimientos(
                        idCategoria,
                        status);

        cargarTablaFiltrada(lista);
    }//GEN-LAST:event_jButton_filtrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton_filtrar;
    private javax.swing.JButton jButton_nuevo_equipo_a_mantenimiento;
    public static javax.swing.JComboBox<String> jComboBox_categorias;
    public static javax.swing.JComboBox<String> jComboBox_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_mantenimientos;
    // End of variables declaration//GEN-END:variables

    /*
     * *****************************************************
     * metodo para mostrar todos los equipos registrados
     * *****************************************************
     */
    private void cargarTablaMantenimientos() {

        // Crear el controlador y obtener los equipos
        MantenimientoController controller = new MantenimientoController();
        ArrayList<Mantenimiento> listaMantenimientos = controller.obtenerMantenimientos();

        // Crear las columnas de la tabla
        String[] columnas = {"ID", "Codigo Equipo", "Equipo", "Fecha Inicio", "Fecha Fin", "Descripcion", "Status", "Estado"};

        // Crear el modelo de la tabla y agregar los datos del ArrayList
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columnas);

        jTable_mantenimientos = new JTable(model);
        jScrollPane1.setViewportView(jTable_mantenimientos);

        // Configurar el ancho de las columnas
        jTable_mantenimientos.getColumnModel().getColumn(0).setPreferredWidth(40);  // ID
        jTable_mantenimientos.getColumnModel().getColumn(1).setPreferredWidth(200); // Codigo Equipo
        jTable_mantenimientos.getColumnModel().getColumn(2).setPreferredWidth(200); // Equipo
        jTable_mantenimientos.getColumnModel().getColumn(3).setPreferredWidth(200); // Fecha Inicio
        jTable_mantenimientos.getColumnModel().getColumn(4).setPreferredWidth(200); // Fecha Fin
        jTable_mantenimientos.getColumnModel().getColumn(5).setPreferredWidth(400); // Descripcion
        jTable_mantenimientos.getColumnModel().getColumn(6).setPreferredWidth(200); // Descripcion
        jTable_mantenimientos.getColumnModel().getColumn(7).setPreferredWidth(200); // estado

        this.CargarEstilos();
        // Llenar el modelo con los datos del ArrayList<Mantenimiento>
        for (Mantenimiento mantenimiento : listaMantenimientos) {
            Object[] fila = {
                mantenimiento.getIdMantenimiento(),
                mantenimiento.getEquipo().getCodigo(),
                mantenimiento.getEquipo().getNombre(),
                mantenimiento.getFechaFin(),
                mantenimiento.getFechaFin(),
                mantenimiento.getDescripcion(),
                mantenimiento.getEquipo().getStatus(),
                mantenimiento.getEstado()
            };
            model.addRow(fila);
        }

        //evento para obtener campo al cual el usuario da click
        //y obtener la interfaz que mostrara la informacion general
        jTable_mantenimientos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_mantenimientos.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idMantenimiento = (int) model.getValueAt(fila_point, columna_point);
                    controller.enviarDatosAModal(idMantenimiento);//metodo
                    System.out.println("idMantenimiento: " + idMantenimiento);
                }
            }
        });
    }

    /**
     * Metodo para cargar las categorias
     */
    private void cargarComboCategorias() {
        java.sql.Connection cn = Conexion.conectar();
        String sql = "select * from categoria";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_categorias.removeAllItems();
            jComboBox_categorias.addItem("Seleccione Categoria:");
            while (rs.next()) {
                jComboBox_categorias.addItem(rs.getString("nombre"));
            }
        } catch (SQLException e) {
            System.out.println("Error al cargar las categorias");
        }
    }

    /**
     * Metodo para obtener id de la categoria
     */
    private int obtenerIdCategoria() {
        String sql = "select * from categoria where nombre = '" + jComboBox_categorias.getSelectedItem() + "'";
        Statement st;
        try {
            java.sql.Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                idCategoria = rs.getInt("id_categoria");
            }
        } catch (SQLException e) {
            System.out.println("Error al obener id de la categoria");
        }
        return idCategoria;
    }
    /**
     * Metodo para recargar la tabla filtrada
     */
    private void cargarTablaFiltrada(
            ArrayList<Mantenimiento> lista) {

        DefaultTableModel model
                = (DefaultTableModel) jTable_mantenimientos.getModel();

        model.setRowCount(0);

        for (Mantenimiento mantenimiento : lista) {

            Object[] fila = {
                mantenimiento.getIdMantenimiento(),
                mantenimiento.getEquipo().getCodigo(),
                mantenimiento.getEquipo().getNombre(),
                mantenimiento.getFechaInicio(),
                mantenimiento.getFechaFin(),
                mantenimiento.getDescripcion(),
                mantenimiento.getEquipo().getStatus(),
                mantenimiento.getEstado()
            };

            model.addRow(fila);
        }
    }
}
