package vista;

import controlador.CategoriaController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import modelo.Categoria;

/**
 *
 * @author Grupo 3 -
 */
public class InterCategoria extends javax.swing.JInternalFrame {

    public static int idCategoria = 0;

    public InterCategoria() {
        initComponents();
        this.setResizable(false);
        this.setSize(1130, 550);
        this.setTitle("Módulo de Administración de Categorias");
        this.cargarTablaCategorias();
        this.CargarEstilos();
    }

    /**
     * Metodo para aplicar los estilos a la tabla
     */
    private void CargarEstilos() {
        // ESTILOS
        // Estilos del encabezado del jtable
        JTableHeader header = jTable_categorias.getTableHeader();
        header.setFont(new Font("Serif", Font.BOLD, 18));  // Fuente negrita para el encabezado
        header.setBackground(Color.WHITE);  // Fondo del encabezado
        header.setForeground(new Color(11, 34, 97));  // Color de Texto del encabezado
        // Cambiar la fuente de la tabla
        jTable_categorias.setFont(new Font("Serif", Font.PLAIN, 20));
        // Cambiar el color de fondo de las celdas seleccionadas
        jTable_categorias.setSelectionBackground(new Color(0, 255, 255));
        // Cambiar el color del texto de las celdas seleccionadas
        jTable_categorias.setSelectionForeground(new Color(30, 119, 37));
        // Cambiar el color de la cuadrícula
        jTable_categorias.setGridColor(Color.BLACK);
        // Ajusta la altura de las filas de la tabla
        jTable_categorias.setRowHeight(30);
        // Crear un borde para solo la parte inferior
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_nueva_categoria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_categorias = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRACIÓN DE CATEGORIAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1080, -1));

        jButton_nueva_categoria.setBackground(new java.awt.Color(255, 255, 153));
        jButton_nueva_categoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_nueva_categoria.setForeground(new java.awt.Color(0, 102, 255));
        jButton_nueva_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jButton_nueva_categoria.setText("NUEVA CATEGORIA");
        jButton_nueva_categoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_nueva_categoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_nueva_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nueva_categoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_nueva_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 100));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(480, 402));

        jTable_categorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_categorias.setPreferredSize(new java.awt.Dimension(400, 80));
        jScrollPane1.setViewportView(jTable_categorias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 920, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_nueva_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nueva_categoriaActionPerformed
        // Crear una instancia del dialogo
        NuevaCategoriaDialogForm dialog = new NuevaCategoriaDialogForm((JFrame) SwingUtilities.getWindowAncestor(InterCategoria.this), true);
        // Mostrar el dialogo de forma modal
        NuevaCategoriaDialogForm.jButton_actualizar.setEnabled(false);
        NuevaCategoriaDialogForm.jButton_guardar.setEnabled(true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton_nueva_categoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_nueva_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_categorias;
    // End of variables declaration//GEN-END:variables

    /*
     * *****************************************************
     * metodo para mostrar todos las categorias registradas
     * *****************************************************
     */
    private void cargarTablaCategorias() {

        // Crear el controlador y obtener los usuarios
        CategoriaController controller = new CategoriaController();
        ArrayList<Categoria> listaCategorias = controller.obtenerCategorias();

        // Crear las columnas de la tabla
        String[] columnas = {"ID", "Nombres", "Descripcion", "Estado"};

        // Crear el modelo de la tabla y agregar los datos del ArrayList
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columnas);

        jTable_categorias = new JTable(model);
        jScrollPane1.setViewportView(jTable_categorias);

        // Configurar el ancho de las columnas
        jTable_categorias.getColumnModel().getColumn(0).setPreferredWidth(40);  // ID
        jTable_categorias.getColumnModel().getColumn(1).setPreferredWidth(350); // Nombres
        jTable_categorias.getColumnModel().getColumn(2).setPreferredWidth(600); // Descripcion
        jTable_categorias.getColumnModel().getColumn(3).setPreferredWidth(250); // Estado

        this.CargarEstilos();
        // Llenar el modelo con los datos del ArrayList<Usuario>
        for (Categoria categoria : listaCategorias) {
            Object[] fila = {
                categoria.getIdCategoria(),
                categoria.getNombre(),
                categoria.getDescripcion(),
                categoria.getEstado()
            };
            model.addRow(fila);
        }

        //evento para obtener campo al cual el usuario da click
        //y obtener la interfaz que mostrara la informacion general
        jTable_categorias.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_categorias.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idCategoria = (int) model.getValueAt(fila_point, columna_point);
                    controller.enviarDatosAModal(idCategoria);//metodo
                }
            }
        });
    }
}
