package vista;

import controlador.EquipoController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import modelo.Equipo;

/**
 *
 * @author Grupo 3 -
 */
public class InterEquipo extends javax.swing.JInternalFrame {

    public static int idEquipo = 0;
    public static int tipoGrafica = 0;

    public InterEquipo() {
        initComponents();
        this.setResizable(false);
        this.setSize(1300, 550);
        this.setTitle("Módulo de Administración de Equipos");

        this.cargarTablaEquipos();
        this.CargarEstilos();

        txt_busqueda.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                buscarEquipo();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                buscarEquipo();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                buscarEquipo();
            }
        });
    }

    /**
     * Metodo para aplicar los estilos a la tabla
     */
    private void CargarEstilos() {
        // ESTILOS
        // Estilos del encabezado del jtable
        JTableHeader header = jTable_equipos.getTableHeader();
        header.setFont(new Font("Serif", Font.BOLD, 18));  // Fuente negrita para el encabezado
        header.setBackground(Color.WHITE);  // Fondo del encabezado
        header.setForeground(new Color(11, 34, 97));  // Color de Texto del encabezado
        // Cambiar la fuente de la tabla
        jTable_equipos.setFont(new Font("Serif", Font.PLAIN, 20));
        // Cambiar el color de fondo de las celdas seleccionadas
        jTable_equipos.setSelectionBackground(new Color(0, 255, 255));
        // Cambiar el color del texto de las celdas seleccionadas
        jTable_equipos.setSelectionForeground(new Color(30, 119, 37));
        // Cambiar el color de la cuadrícula
        jTable_equipos.setGridColor(Color.BLACK);
        // Ajusta la altura de las filas de la tabla
        jTable_equipos.setRowHeight(30);
        // Crear un borde para solo la parte inferior
        Border bottomBorder = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK);
        txt_busqueda.setBorder(bottomBorder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_nuevo_equipo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_equipos = new javax.swing.JTable();
        txt_busqueda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton_graficas_equipos = new javax.swing.JButton();
        jButton_graficas_equipos1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRACIÓN DE EQUIPOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1230, -1));

        jButton_nuevo_equipo.setBackground(new java.awt.Color(204, 255, 255));
        jButton_nuevo_equipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_nuevo_equipo.setForeground(new java.awt.Color(0, 102, 255));
        jButton_nuevo_equipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nueva-pestana.png"))); // NOI18N
        jButton_nuevo_equipo.setText("NUEVO EQUIPO");
        jButton_nuevo_equipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_nuevo_equipo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_nuevo_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevo_equipoActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_nuevo_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 100));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(480, 402));

        jTable_equipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_equipos.setPreferredSize(new java.awt.Dimension(400, 80));
        jScrollPane1.setViewportView(jTable_equipos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 1070, 380));

        txt_busqueda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(txt_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, 300, 40));

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 430, 40, 40));

        jButton_graficas_equipos.setBackground(new java.awt.Color(255, 255, 102));
        jButton_graficas_equipos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_graficas_equipos.setForeground(new java.awt.Color(0, 0, 102));
        jButton_graficas_equipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barra-grafica.png"))); // NOI18N
        jButton_graficas_equipos.setText("Graficar / Status");
        jButton_graficas_equipos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_graficas_equipos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_graficas_equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_graficas_equiposActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_graficas_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 100));

        jButton_graficas_equipos1.setBackground(new java.awt.Color(51, 255, 51));
        jButton_graficas_equipos1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_graficas_equipos1.setForeground(new java.awt.Color(0, 0, 102));
        jButton_graficas_equipos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crecimiento.png"))); // NOI18N
        jButton_graficas_equipos1.setText("Graficar Categorias");
        jButton_graficas_equipos1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_graficas_equipos1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_graficas_equipos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_graficas_equipos1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_graficas_equipos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 150, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_nuevo_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevo_equipoActionPerformed
        // Crear una instancia del dialogo
        NuevoEquipoDialogForm dialog = new NuevoEquipoDialogForm((JFrame) SwingUtilities.getWindowAncestor(InterEquipo.this), true);
        // Mostrar el dialogo de forma modal
        NuevoEquipoDialogForm.jButton_actualizar.setEnabled(false);
        NuevoEquipoDialogForm.jButton_guardar.setEnabled(true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton_nuevo_equipoActionPerformed

    private void jButton_graficas_equiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_graficas_equiposActionPerformed
        tipoGrafica = 1;
        InterGraficaEquipos vista
                = new InterGraficaEquipos();

        JDesktopPane desktop
                = MenuAdmin.jDesktopPane_menu;

        desktop.add(vista);

        int x = (MenuAdmin.jDesktopPane_menu.getWidth() - vista.getWidth()) / 2;
        int y = (MenuAdmin.jDesktopPane_menu.getHeight() - vista.getHeight()) / 2;
        vista.setLocation(x, y);
        vista.setVisible(true);

    }//GEN-LAST:event_jButton_graficas_equiposActionPerformed

    private void jButton_graficas_equipos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_graficas_equipos1ActionPerformed
        tipoGrafica = 2;

        InterGraficaEquipos vista
                = new InterGraficaEquipos();

        JDesktopPane desktop
                = MenuAdmin.jDesktopPane_menu;

        desktop.add(vista);

        int x = (MenuAdmin.jDesktopPane_menu.getWidth() - vista.getWidth()) / 2;
        int y = (MenuAdmin.jDesktopPane_menu.getHeight() - vista.getHeight()) / 2;
        vista.setLocation(x, y);
        vista.setVisible(true);

    }//GEN-LAST:event_jButton_graficas_equipos1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_graficas_equipos;
    private javax.swing.JButton jButton_graficas_equipos1;
    private javax.swing.JButton jButton_nuevo_equipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_equipos;
    private javax.swing.JTextField txt_busqueda;
    // End of variables declaration//GEN-END:variables

    /*
     * *****************************************************
     * metodo para mostrar todos los equipos registrados
     * *****************************************************
     */
    private void cargarTablaEquipos() {

        // Crear el controlador y obtener los equipos
        EquipoController controller = new EquipoController();
        ArrayList<Equipo> listaEquipos = controller.obtenerEquipos();

        // Crear las columnas de la tabla
        String[] columnas = {"ID", "Categoria", "Ubicacion", "Codigo", "Nombre", "Marca", "Modelo", "Status", "Estado"};

        // Crear el modelo de la tabla y agregar los datos del ArrayList
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columnas);

        jTable_equipos = new JTable(model);
        jScrollPane1.setViewportView(jTable_equipos);

        // Configurar el ancho de las columnas
        jTable_equipos.getColumnModel().getColumn(0).setPreferredWidth(40);  // ID
        jTable_equipos.getColumnModel().getColumn(1).setPreferredWidth(200); // Categoria
        jTable_equipos.getColumnModel().getColumn(2).setPreferredWidth(200); // Ubicacion
        jTable_equipos.getColumnModel().getColumn(3).setPreferredWidth(150); // Codigo
        jTable_equipos.getColumnModel().getColumn(4).setPreferredWidth(300); // Nombre
        jTable_equipos.getColumnModel().getColumn(5).setPreferredWidth(150); // Marca
        jTable_equipos.getColumnModel().getColumn(6).setPreferredWidth(200); // Modelo
        jTable_equipos.getColumnModel().getColumn(7).setPreferredWidth(200); // status
        jTable_equipos.getColumnModel().getColumn(8).setPreferredWidth(200); // estado

        this.CargarEstilos();
        // Llenar el modelo con los datos del ArrayList<Equipo>
        for (Equipo equipo : listaEquipos) {
            Object[] fila = {
                equipo.getIdEquipo(),
                equipo.getCategoria().getNombre(),
                equipo.getUbicacion().getNombre(),
                equipo.getCodigo(),
                equipo.getNombre(),
                equipo.getMarca(),
                equipo.getModelo(),
                equipo.getStatus(),
                equipo.getEstado()
            };
            model.addRow(fila);
        }

        //evento para obtener campo al cual el usuario da click
        //y obtener la interfaz que mostrara la informacion general
        jTable_equipos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_equipos.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idEquipo = (int) model.getValueAt(fila_point, columna_point);
                    controller.enviarDatosAModal(idEquipo);//metodo
                }
            }
        });
    }

    /**
     * Metodo para ejecutar la busqueda
     */
    private void buscarEquipo() {

        EquipoController controller = new EquipoController();

        ArrayList<Equipo> listaEquipos
                = controller.obtenerEquiposBusqueda(
                        txt_busqueda.getText().trim());

        String[] columnas = {
            "ID",
            "Categoria",
            "Ubicacion",
            "Codigo",
            "Nombre",
            "Marca",
            "Modelo",
            "Status",
            "Estado"
        };

        DefaultTableModel model
                = new DefaultTableModel();

        model.setColumnIdentifiers(columnas);

        jTable_equipos = new JTable(model);
        jScrollPane1.setViewportView(jTable_equipos);

        // Anchos
        jTable_equipos.getColumnModel()
                .getColumn(0).setPreferredWidth(40);

        jTable_equipos.getColumnModel()
                .getColumn(1).setPreferredWidth(200);

        jTable_equipos.getColumnModel()
                .getColumn(2).setPreferredWidth(200);

        jTable_equipos.getColumnModel()
                .getColumn(3).setPreferredWidth(150);

        jTable_equipos.getColumnModel()
                .getColumn(4).setPreferredWidth(300);

        jTable_equipos.getColumnModel()
                .getColumn(5).setPreferredWidth(150);

        jTable_equipos.getColumnModel()
                .getColumn(6).setPreferredWidth(200);

        jTable_equipos.getColumnModel()
                .getColumn(7).setPreferredWidth(150);

        jTable_equipos.getColumnModel()
                .getColumn(8).setPreferredWidth(150);

        this.CargarEstilos();

        for (Equipo equipo : listaEquipos) {

            Object[] fila = {
                equipo.getIdEquipo(),
                equipo.getCategoria().getNombre(),
                equipo.getUbicacion().getNombre(),
                equipo.getCodigo(),
                equipo.getNombre(),
                equipo.getMarca(),
                equipo.getModelo(),
                equipo.getStatus(),
                equipo.getEstado()
            };

            model.addRow(fila);
        }

        jTable_equipos.addMouseListener(
                new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {

                int fila
                        = jTable_equipos.rowAtPoint(
                                e.getPoint());

                if (fila > -1) {

                    idEquipo
                            = (int) model.getValueAt(
                                    fila, 0);

                    controller.enviarDatosAModal(
                            idEquipo);
                }
            }
        });
    }
}
