package vista;

import controlador.EquipoController;
import java.util.Map;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;

import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Edison Zambrano
 */
public class InterGraficaEquipos extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterGraficaEquipos
     */
    public InterGraficaEquipos() {
        initComponents();
        setTitle("Graficas");
        this.setResizable(false);
        this.setSize(600, 400);

        cargarGraficaPastel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 580, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private void cargarGraficaPastel() {

        EquipoController controlador = new EquipoController();
        String sql = "";
        if (InterEquipo.tipoGrafica == 1) {
            Map<String, Integer> datos
                    = controlador.obtenerCantidadEquiposPorEstado();

            DefaultPieDataset dataset
                    = new DefaultPieDataset();

            for (Map.Entry<String, Integer> entry : datos.entrySet()) {

                dataset.setValue(
                        entry.getKey(),
                        entry.getValue()
                );
            }
            JFreeChart chart
                    = ChartFactory.createPieChart(
                            "Equipos por Status",
                            dataset,
                            true,
                            true,
                            false
                    );

            ChartPanel panelGrafica
                    = new ChartPanel(chart);

            panelGrafica.setPreferredSize(
                    new java.awt.Dimension(
                            600,
                            400
                    )
            );

            jPanel1.removeAll();

            jPanel1.setLayout(
                    new java.awt.BorderLayout()
            );

            jPanel1.add(
                    panelGrafica,
                    java.awt.BorderLayout.CENTER
            );

            jPanel1.validate();
        } else if (InterEquipo.tipoGrafica == 2) {
            Map<String, Integer> datos
                    = controlador.obtenerCantidadEquiposPorCategoria();

            DefaultPieDataset dataset
                    = new DefaultPieDataset();

            for (Map.Entry<String, Integer> entry : datos.entrySet()) {

                dataset.setValue(
                        entry.getKey(),
                        entry.getValue()
                );
            }
            JFreeChart chart
                    = ChartFactory.createPieChart(
                            "Equipos por Categorias",
                            dataset,
                            true,
                            true,
                            false
                    );

            ChartPanel panelGrafica
                    = new ChartPanel(chart);

            panelGrafica.setPreferredSize(
                    new java.awt.Dimension(
                            600,
                            400
                    )
            );

            jPanel1.removeAll();

            jPanel1.setLayout(
                    new java.awt.BorderLayout()
            );

            jPanel1.add(
                    panelGrafica,
                    java.awt.BorderLayout.CENTER
            );

            jPanel1.validate();
        }

    }
}
