package vista;

import java.awt.Dimension;
import javax.swing.JDesktopPane;
import modelo.Sesion;

/**
 *
 * @author Grupo 3 -
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public static JDesktopPane jDesktopPane_menu;

    public MenuAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setResizable(false);
        this.setTitle("SISTEMA INVENTARIO ACADEMICO - ADMIN");
        this.setSize(new Dimension(1200, 500));
        this.setExtendedState(MAXIMIZED_BOTH);

        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        jDesktopPane_menu.setBounds(0, 60, ancho, (alto - 170));
        this.add(jDesktopPane_menu);
        
        //validar permisos
         //validarPermisos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_title = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_usuario = new javax.swing.JMenu();
        jMenuItem_usuarios = new javax.swing.JMenuItem();
        jMenu_equipos = new javax.swing.JMenu();
        jMenuItem_equipos = new javax.swing.JMenuItem();
        jMenu_categorias = new javax.swing.JMenu();
        jMenuItem_categorias = new javax.swing.JMenuItem();
        jMenu_ubicacion = new javax.swing.JMenu();
        jMenuItem_ubicacion = new javax.swing.JMenuItem();
        jMenu_mantenimiento = new javax.swing.JMenu();
        jMenuItem_mantenimientos = new javax.swing.JMenuItem();
        jMenu_cerrar_sesion = new javax.swing.JMenu();
        jMenuItem_cerrar_sesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel_title.setFont(new java.awt.Font("Centaur", 1, 48)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_title.setText("SISTEMA INVENTARIO ACADEMICO");
        jLabel_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_title.setPreferredSize(new java.awt.Dimension(503, 50));
        jPanel1.add(jLabel_title, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 70));

        jMenu_usuario.setForeground(new java.awt.Color(0, 0, 153));
        jMenu_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMenu_usuario.setText("Usuarios");
        jMenu_usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu_usuario.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_usuarios.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMenuItem_usuarios.setText("Usuarios");
        jMenuItem_usuarios.setPreferredSize(new java.awt.Dimension(200, 40));
        jMenuItem_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_usuariosActionPerformed(evt);
            }
        });
        jMenu_usuario.add(jMenuItem_usuarios);

        jMenuBar1.add(jMenu_usuario);

        jMenu_equipos.setForeground(new java.awt.Color(0, 0, 153));
        jMenu_equipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/equipo.png"))); // NOI18N
        jMenu_equipos.setText("Equipos");
        jMenu_equipos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu_equipos.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_equipos.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem_equipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/equipo.png"))); // NOI18N
        jMenuItem_equipos.setText("Admin Equipos");
        jMenuItem_equipos.setPreferredSize(new java.awt.Dimension(200, 40));
        jMenuItem_equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_equiposActionPerformed(evt);
            }
        });
        jMenu_equipos.add(jMenuItem_equipos);

        jMenuBar1.add(jMenu_equipos);

        jMenu_categorias.setForeground(new java.awt.Color(0, 0, 153));
        jMenu_categorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/asistencia.png"))); // NOI18N
        jMenu_categorias.setText("Categorias");
        jMenu_categorias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu_categorias.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_categorias.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem_categorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/asistencia.png"))); // NOI18N
        jMenuItem_categorias.setText("Admin Categorias");
        jMenuItem_categorias.setPreferredSize(new java.awt.Dimension(200, 40));
        jMenuItem_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_categoriasActionPerformed(evt);
            }
        });
        jMenu_categorias.add(jMenuItem_categorias);

        jMenuBar1.add(jMenu_categorias);

        jMenu_ubicacion.setForeground(new java.awt.Color(0, 0, 153));
        jMenu_ubicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ubicacion.png"))); // NOI18N
        jMenu_ubicacion.setText("Ubicacion");
        jMenu_ubicacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu_ubicacion.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_ubicacion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem_ubicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio.png"))); // NOI18N
        jMenuItem_ubicacion.setText("Admin Ubicacion");
        jMenuItem_ubicacion.setPreferredSize(new java.awt.Dimension(200, 40));
        jMenuItem_ubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ubicacionActionPerformed(evt);
            }
        });
        jMenu_ubicacion.add(jMenuItem_ubicacion);

        jMenuBar1.add(jMenu_ubicacion);

        jMenu_mantenimiento.setForeground(new java.awt.Color(0, 0, 153));
        jMenu_mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mantenimiento.png"))); // NOI18N
        jMenu_mantenimiento.setText("Mantenimiento");
        jMenu_mantenimiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu_mantenimiento.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem_mantenimientos.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem_mantenimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/curso.png"))); // NOI18N
        jMenuItem_mantenimientos.setText("Admin Mantenimientos");
        jMenuItem_mantenimientos.setPreferredSize(new java.awt.Dimension(200, 40));
        jMenuItem_mantenimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_mantenimientosActionPerformed(evt);
            }
        });
        jMenu_mantenimiento.add(jMenuItem_mantenimientos);

        jMenuBar1.add(jMenu_mantenimiento);

        jMenu_cerrar_sesion.setForeground(new java.awt.Color(0, 0, 153));
        jMenu_cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jMenu_cerrar_sesion.setText("Cerrar Sesion");
        jMenu_cerrar_sesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu_cerrar_sesion.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem_cerrar_sesion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem_cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jMenuItem_cerrar_sesion.setText("Cerrar Sesion");
        jMenuItem_cerrar_sesion.setPreferredSize(new java.awt.Dimension(200, 40));
        jMenuItem_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_cerrar_sesionActionPerformed(evt);
            }
        });
        jMenu_cerrar_sesion.add(jMenuItem_cerrar_sesion);

        jMenuBar1.add(jMenu_cerrar_sesion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_usuariosActionPerformed
        InterUsuario inter = new InterUsuario();
        jDesktopPane_menu.add(inter);
        // Calcular el centro
        int x = (jDesktopPane_menu.getWidth() - inter.getWidth()) / 2;
        int y = (jDesktopPane_menu.getHeight() - inter.getHeight()) / 2;

        // Establecer la ubicación centrada
        inter.setLocation(x, y);
        inter.setVisible(true);
    }//GEN-LAST:event_jMenuItem_usuariosActionPerformed

    private void jMenuItem_equiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_equiposActionPerformed
        InterEquipo inter = new InterEquipo();
        jDesktopPane_menu.add(inter);
        // Calcular el centro
        int x = (jDesktopPane_menu.getWidth() - inter.getWidth()) / 2;
        int y = (jDesktopPane_menu.getHeight() - inter.getHeight()) / 2;

        // Establecer la ubicación centrada
        inter.setLocation(x, y);
        inter.setVisible(true);
    }//GEN-LAST:event_jMenuItem_equiposActionPerformed

    private void jMenuItem_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_categoriasActionPerformed
        InterCategoria inter = new InterCategoria();
        jDesktopPane_menu.add(inter);
        // Calcular el centro
        int x = (jDesktopPane_menu.getWidth() - inter.getWidth()) / 2;
        int y = (jDesktopPane_menu.getHeight() - inter.getHeight()) / 2;

        // Establecer la ubicación centrada
        inter.setLocation(x, y);
        inter.setVisible(true);
    }//GEN-LAST:event_jMenuItem_categoriasActionPerformed

    private void jMenuItem_ubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ubicacionActionPerformed
        InterUbicacion inter = new InterUbicacion();
        jDesktopPane_menu.add(inter);
        // Calcular el centro
        int x = (jDesktopPane_menu.getWidth() - inter.getWidth()) / 2;
        int y = (jDesktopPane_menu.getHeight() - inter.getHeight()) / 2;

        // Establecer la ubicación centrada
        inter.setLocation(x, y);
        inter.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ubicacionActionPerformed

    private void jMenuItem_mantenimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_mantenimientosActionPerformed
        InterMantenimiento inter = new InterMantenimiento();
        jDesktopPane_menu.add(inter);
        // Calcular el centro
        int x = (jDesktopPane_menu.getWidth() - inter.getWidth()) / 2;
        int y = (jDesktopPane_menu.getHeight() - inter.getHeight()) / 2;

        // Establecer la ubicación centrada
        inter.setLocation(x, y);
        inter.setVisible(true);
    }//GEN-LAST:event_jMenuItem_mantenimientosActionPerformed

    private void jMenuItem_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_cerrar_sesionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_cerrar_sesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabel_title;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_categorias;
    private javax.swing.JMenuItem jMenuItem_cerrar_sesion;
    private javax.swing.JMenuItem jMenuItem_equipos;
    private javax.swing.JMenuItem jMenuItem_mantenimientos;
    private javax.swing.JMenuItem jMenuItem_ubicacion;
    private javax.swing.JMenuItem jMenuItem_usuarios;
    private javax.swing.JMenu jMenu_categorias;
    private javax.swing.JMenu jMenu_cerrar_sesion;
    private javax.swing.JMenu jMenu_equipos;
    private javax.swing.JMenu jMenu_mantenimiento;
    private javax.swing.JMenu jMenu_ubicacion;
    private javax.swing.JMenu jMenu_usuario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    //metodo para validar permisos de Usuario
    private void validarPermisos() {

        int rol = Sesion.usuarioLogueado.getTipo_usuario().getIdTipoUsuario();

        switch (rol) {

            case 1: // Administrador

                break;

            case 2: // Operador

                jMenu_usuario.setVisible(false);

                break;

            case 3: // Invitado

                jMenu_usuario.setVisible(false);
                jMenu_equipos.setVisible(false);
                jMenu_categorias.setVisible(false);
                jMenu_ubicacion.setVisible(false);

                break;
        }
    }
}
