package vista;

import conexion.Conexion;
import controlador.EquipoController;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import modelo.Categoria;
import modelo.Equipo;
import modelo.Ubicacion;
import static vista.InterEquipo.jTable_equipos;

/**
 *
 * @author Grupo 3
 */
public class NuevoEquipoDialogForm extends javax.swing.JDialog {

    private static int idEquipo = InterEquipo.idEquipo;
    private int idCategoria = 0, idUbicacion = 0;

    public NuevoEquipoDialogForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Nuevo Equipo");
        setLayout(null);
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        // Crear un borde para solo la parte inferior
        Border bottomBorder = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK);

        // Aplicar el borde solo al JTextField
        txt_codigo.setBorder(bottomBorder);
        txt_nombre.setBorder(bottomBorder);
        txt_marca.setBorder(bottomBorder);
        txt_modelo.setBorder(bottomBorder);
        txt_status.setBorder(bottomBorder);
        jComboBox_ubicaciones.setBackground(Color.LIGHT_GRAY); // Fondo del JComboBox
        jComboBox_categorias.setBackground(Color.LIGHT_GRAY); // Fondo del JComboBox
        jComboBox_estado.setBackground(Color.LIGHT_GRAY); // Fondo del JComboBox

        //cargar metodos
        cargarComboCategorias();
        cargarComboUbicaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jButton_guardar = new javax.swing.JButton();
        jButton_actualizar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_ubicaciones = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox_estado = new javax.swing.JComboBox<>();
        txt_marca = new javax.swing.JTextField();
        jComboBox_categorias = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Categorias:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Ubicaciones:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Codigo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Nombre:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Modelo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        txt_modelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 250, 30));

        txt_codigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 250, 30));

        txt_nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 250, 30));

        jButton_guardar.setBackground(new java.awt.Color(0, 102, 255));
        jButton_guardar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        jButton_guardar.setText("GUARDAR");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 200, 40));

        jButton_actualizar.setBackground(new java.awt.Color(0, 204, 102));
        jButton_actualizar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        jButton_actualizar.setText("ACTUALIZAR");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 200, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Marca:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jComboBox_ubicaciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_ubicaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Ubicacion:" }));
        jPanel1.add(jComboBox_ubicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 250, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("Status:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        txt_status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 250, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Estado:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        jComboBox_estado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jPanel1.add(jComboBox_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 250, 30));

        txt_marca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 250, 30));

        jComboBox_categorias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Categoria:" }));
        jPanel1.add(jComboBox_categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 600, 530));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS DEL EQUIPO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 10, 600, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed

        String categoria = jComboBox_categorias.getSelectedItem().toString();
        String ubicacion = jComboBox_ubicaciones.getSelectedItem().toString();
        String codigo = txt_codigo.getText().trim();
        String nombre = txt_nombre.getText().trim();
        String marca = txt_marca.getText().trim();
        String modelo = txt_modelo.getText().trim();
        String status = txt_status.getText().trim();
        String estado = jComboBox_estado.getSelectedItem().toString();
        //validamos campos vacios
        if (codigo.isEmpty() || nombre.isEmpty() || marca.isEmpty()
                || modelo.isEmpty() || status.isEmpty() || categoria.equals("Seleccione Categoria:") || ubicacion.equals("Seleccione Ubicacion:")) {
            JOptionPane.showMessageDialog(null, "¡Complete todos los campos!");
        } else {
            EquipoController equipoController = new EquipoController();

            Equipo equipo = new Equipo();
            Categoria categoriaObjeto = new Categoria();
            Ubicacion ubicacionObjeto = new Ubicacion();

            equipo.setIdEquipo(0);
            //--
            categoriaObjeto.setIdCategoria(jComboBox_categorias.getSelectedIndex());
            equipo.setCategoria(categoriaObjeto);
            ubicacionObjeto.setIdUbicacion(jComboBox_ubicaciones.getSelectedIndex());
            equipo.setUbicacion(ubicacionObjeto);
            //--
            equipo.setCodigo(codigo);
            equipo.setNombre(nombre);
            equipo.setMarca(marca);
            equipo.setModelo(modelo);
            equipo.setStatus(status);
            equipo.setEstado(estado);
            //metodo guardar
            if (equipoController.guardar(equipo)) {
                JOptionPane.showMessageDialog(null, "¡Equipo Guardado!");
                //vaciar los campos
                jComboBox_categorias.setSelectedItem("Seleccione Categoria:");
                jComboBox_ubicaciones.setSelectedItem("Seleccione Ubicacion:");
                txt_codigo.setText("");
                txt_nombre.setText("");
                txt_marca.setText("");
                txt_modelo.setText("");
                txt_status.setText("");
                jComboBox_estado.setSelectedItem("Activo");

                //Cargar la tabla para actualizar los registros
                this.cargarTablaEquipos();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al Guardar!");

            }
        }
    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed

        String categoria = jComboBox_categorias.getSelectedItem().toString();
        String ubicacion = jComboBox_ubicaciones.getSelectedItem().toString();
        String codigo = txt_codigo.getText().trim();
        String nombre = txt_nombre.getText().trim();
        String marca = txt_marca.getText().trim();
        String modelo = txt_modelo.getText().trim();
        String status = txt_status.getText().trim();
        String estado = jComboBox_estado.getSelectedItem().toString();
        //validamos campos vacios
        if (codigo.isEmpty() || nombre.isEmpty() || marca.isEmpty()
                || modelo.isEmpty() || status.isEmpty() || categoria.equals("Seleccione Categoria:") || ubicacion.equals("Seleccione Ubicacion:")) {
            JOptionPane.showMessageDialog(null, "¡Complete todos los campos!");
        } else {
            EquipoController equipoController = new EquipoController();

            Equipo equipo = new Equipo();
            Categoria categoriaObjeto = new Categoria();
            Ubicacion ubicacionObjeto = new Ubicacion();

            equipo.setIdEquipo(0);
            //--
            categoriaObjeto.setIdCategoria(obtenerIdCategoria());
            equipo.setCategoria(categoriaObjeto);
            ubicacionObjeto.setIdUbicacion(obtenerIdUbicacion());
            equipo.setUbicacion(ubicacionObjeto);
            //--
            equipo.setCodigo(codigo);
            equipo.setNombre(nombre);
            equipo.setMarca(marca);
            equipo.setModelo(modelo);
            equipo.setStatus(status);
            equipo.setEstado(estado);
            //metodo guardar
            if (equipoController.actualizar(equipo, idEquipo)) {
                JOptionPane.showMessageDialog(null, "¡Equipo Actualizado!");
                //vaciar los campos
                jComboBox_categorias.setSelectedItem("Seleccione Categoria:");
                jComboBox_ubicaciones.setSelectedItem("Seleccione Ubicacion:");
                txt_codigo.setText("");
                txt_nombre.setText("");
                txt_marca.setText("");
                txt_modelo.setText("");
                txt_status.setText("");
                jComboBox_estado.setSelectedItem("Activo");

                //Cargar la tabla para actualizar los registros
                this.cargarTablaEquipos();
//                        System.out.println("Helloooo!!!!!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al Actualizar!");

            }
        }
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoEquipoDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoEquipoDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoEquipoDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoEquipoDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoEquipoDialogForm dialog = new NuevoEquipoDialogForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton_actualizar;
    public static javax.swing.JButton jButton_guardar;
    public static javax.swing.JComboBox<String> jComboBox_categorias;
    public static javax.swing.JComboBox<String> jComboBox_estado;
    public static javax.swing.JComboBox<String> jComboBox_ubicaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField txt_codigo;
    public static javax.swing.JTextField txt_marca;
    public static javax.swing.JTextField txt_modelo;
    public static javax.swing.JTextField txt_nombre;
    public static javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo para aplicar los estilos a la tabla
     */
    private void CargarEstilos() {
        // Estilos del encabezado del jtable
        JTableHeader header = InterEquipo.jTable_equipos.getTableHeader();
        header.setFont(new Font("Serif", Font.BOLD, 18));  // Fuente negrita para el encabezado
        header.setBackground(Color.WHITE);  // Fondo del encabezado
        header.setForeground(new Color(11, 34, 97));  // Color de Texto del encabezado
        // Cambiar la fuente de la tabla
        InterEquipo.jTable_equipos.setFont(new Font("Serif", Font.PLAIN, 20));
        // Cambiar el color de fondo de las celdas seleccionadas
        InterEquipo.jTable_equipos.setSelectionBackground(new Color(0, 255, 255));
        // Cambiar el color del texto de las celdas seleccionadas
        InterEquipo.jTable_equipos.setSelectionForeground(new Color(30, 119, 37));
        // Cambiar el color de la cuadrícula
        InterEquipo.jTable_equipos.setGridColor(Color.BLACK);
        // Ajusta la altura de las filas de la tabla
        InterEquipo.jTable_equipos.setRowHeight(30);
    }

    private void cargarTablaEquipos() {

        // Crear el controlador y obtener los estudiantes
        EquipoController controller = new EquipoController();
        ArrayList<Equipo> listaEquipos = controller.obtenerEquipos();

        // Crear las columnas de la tabla
        String[] columnas = {"ID", "Categoria", "Ubicacion", "Codigo", "Nombre", "Marca", "Modelo", "Status", "Estado"};

        // Crear el modelo de la tabla y agregar los datos del ArrayList
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columnas);

        InterEquipo.jTable_equipos = new JTable(model);
        InterEquipo.jScrollPane1.setViewportView(InterEquipo.jTable_equipos);

        this.CargarEstilos();

        // Configurar el ancho de las columnas
        jTable_equipos.getColumnModel().getColumn(0).setPreferredWidth(40);  // ID
        jTable_equipos.getColumnModel().getColumn(1).setPreferredWidth(200); // Categoria
        jTable_equipos.getColumnModel().getColumn(2).setPreferredWidth(200); // Ubicacion
        jTable_equipos.getColumnModel().getColumn(3).setPreferredWidth(150); // Codigo
        jTable_equipos.getColumnModel().getColumn(4).setPreferredWidth(300); // Nombre
        jTable_equipos.getColumnModel().getColumn(5).setPreferredWidth(150); // Marca
        jTable_equipos.getColumnModel().getColumn(6).setPreferredWidth(200); // Modelo
        jTable_equipos.getColumnModel().getColumn(7).setPreferredWidth(200); // status
        jTable_equipos.getColumnModel().getColumn(8).setPreferredWidth(200); // estado

        // Llenar el modelo con los datos del ArrayList<Equipo>
        for (Equipo equipo : listaEquipos) {
            Object[] fila = {
                equipo.getIdEquipo(),
                equipo.getCategoria().getDescripcion(),
                equipo.getUbicacion().getDescripcion(),
                equipo.getCodigo(),
                equipo.getNombre(),
                equipo.getMarca(),
                equipo.getModelo(),
                equipo.getStatus(),
                equipo.getEstado()
            };
            model.addRow(fila);
        }

        //evento para obtener campo al cual el usuario da click
        //y obtener la interfaz que mostrara la informacion general
        jTable_equipos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_equipos.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idEquipo = (int) model.getValueAt(fila_point, columna_point);
                    controller.enviarDatosAModal(idEquipo);//metodo
                }
            }
        });
    }

    /**
     * Metodo para cargar las categorias
     */
    private void cargarComboCategorias() {
        java.sql.Connection cn = Conexion.conectar();
        String sql = "select * from categoria";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_categorias.removeAllItems();
            jComboBox_categorias.addItem("Seleccione Categoria:");
            while (rs.next()) {
                jComboBox_categorias.addItem(rs.getString("nombre"));
            }
        } catch (SQLException e) {
            System.out.println("Error al cargar las categorias");
        }
    }

    /**
     * Metodo para obtener id de la categoria
     */
    private int obtenerIdCategoria() {
        String sql = "select * from categoria where nombre = '" + jComboBox_categorias.getSelectedItem() + "'";
        Statement st;
        try {
            java.sql.Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                idCategoria = rs.getInt("id_categoria");
            }
        } catch (SQLException e) {
            System.out.println("Error al obener id de la categoria");
        }
        return idCategoria;
    }

    /**
     * Metodo para cargar las ubicaciones
     */
    private void cargarComboUbicaciones() {
        java.sql.Connection cn = Conexion.conectar();
        String sql = "select * from ubicacion";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_ubicaciones.removeAllItems();
            jComboBox_ubicaciones.addItem("Seleccione Ubicacion:");
            while (rs.next()) {
                jComboBox_ubicaciones.addItem(rs.getString("nombre"));
            }
        } catch (SQLException e) {
            System.out.println("Error al cargar las ubicaciones");
        }
    }

    /**
     * Metodo para obtener id de la ubicacion
     */
    private int obtenerIdUbicacion() {
        String sql = "select * from ubicacion where nombre = '" + jComboBox_ubicaciones.getSelectedItem() + "'";
        Statement st;
        try {
            java.sql.Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                idUbicacion = rs.getInt("id_ubicacion");
            }
        } catch (SQLException e) {
            System.out.println("Error al obener id de la ubicacion");
        }
        return idUbicacion;
    }

}
