package vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import conexion.Conexion;
import controlador.MantenimientoController;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import modelo.Equipo;
import modelo.Mantenimiento;
import static vista.InterMantenimiento.jTable_mantenimientos;

/**
 *
 * @author Grupo 3
 */
public class NuevoMantenimientoDialogForm extends javax.swing.JDialog {

    private static int idMantenimiento = InterMantenimiento.idMantenimiento;
    private int idEquipo = 0;
    private String codigo = "", marca = "";

    public NuevoMantenimientoDialogForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Nuevo Mantenimiento");
        setLayout(null);
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        jComboBox_equipos.setModel(
                new DefaultComboBoxModel<Equipo>()
        );

        // Crear un borde para solo la parte inferior
        Border bottomBorder = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK);

        // Aplicar el borde solo al JTextField
//        txt_codigo.setBorder(bottomBorder);
        jTextArea_descripcion.setBorder(bottomBorder);
//        jDateChooser_fecha_inicio.setBorder(bottomBorder);
//        jDateChooser_fecha_fin.setBorder(bottomBorder);
        jComboBox_equipos.setBackground(Color.LIGHT_GRAY); // Fondo del JComboBox
        jComboBox_estado.setBackground(Color.LIGHT_GRAY); // Fondo del JComboBox

        //cargar metodos
        cargarComboEquipos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        jButton_guardar = new javax.swing.JButton();
        jButton_actualizar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox_estado = new javax.swing.JComboBox<>();
        jComboBox_equipos = new javax.swing.JComboBox();
        jDateChooser_fecha_inicio = new com.toedter.calendar.JDateChooser();
        jDateChooser_fecha_fin = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_descripcion = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jComboBox_status = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Equipos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Codigo Equipo / Marca Equipo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Fecha Fin:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Fecha Fin:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        txt_codigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_codigo.setEnabled(false);
        jPanel1.add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 250, 30));

        jButton_guardar.setBackground(new java.awt.Color(0, 102, 255));
        jButton_guardar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        jButton_guardar.setText("GUARDAR");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 200, 40));

        jButton_actualizar.setBackground(new java.awt.Color(0, 204, 102));
        jButton_actualizar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        jButton_actualizar.setText("ACTUALIZAR");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 200, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Descripcion:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Estado:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jComboBox_estado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jPanel1.add(jComboBox_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 250, 30));

        jComboBox_equipos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_equipos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Equipo:" }));
        jComboBox_equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_equiposActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, 30));
        jPanel1.add(jDateChooser_fecha_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 250, 30));
        jPanel1.add(jDateChooser_fecha_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 250, 30));

        jTextArea_descripcion.setColumns(20);
        jTextArea_descripcion.setRows(5);
        jScrollPane1.setViewportView(jTextArea_descripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 540, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("Status:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        jComboBox_status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo", "Operativo", "En Mantenimiento" }));
        jPanel1.add(jComboBox_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 250, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 600, 530));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS DEL EQUIPO EN MANTENIMIENTO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        String equipo = jComboBox_equipos.getSelectedItem().toString();
        String descripcion = jTextArea_descripcion.getText().trim();
        Date fechaInicioDate = jDateChooser_fecha_inicio.getDate();
        Date fechaFinDate = jDateChooser_fecha_fin.getDate();

        String estado = jComboBox_estado.getSelectedItem().toString();
        //validamos campos vacios
        if (fechaInicioDate == null
                || fechaFinDate == null
                || descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Complete todos los campos!");
        } else {
            Equipo equipoSeleccionado
                    = (Equipo) jComboBox_equipos.getSelectedItem();

            if (equipoSeleccionado == null
                    || equipoSeleccionado.getIdEquipo() == 0) {

                JOptionPane.showMessageDialog(null,
                        "Seleccione un equipo");
                return;
            }

            MantenimientoController mantenimientoController = new MantenimientoController();
            Mantenimiento mantenimiento = new Mantenimiento();
//            Equipo equipoObject = new Equipo();
            LocalDate fechaInicio = fechaInicioDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaFin = fechaFinDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            mantenimiento.setIdMantenimiento(0);
            //--
//            equipoObject.setIdEquipo(equipoObject.getIdEquipo());
//            equipoObject.setNombre(jComboBox_equipos.getSelectedItem().toString());
//            mantenimiento.setEquipo(equipoObject);

            Equipo equipo2
                    = (Equipo) jComboBox_equipos.getSelectedItem();

            mantenimiento.setEquipo(equipo2);
            //--
            mantenimiento.setFechaInicio(fechaInicio);
            mantenimiento.setFechaFin(fechaFin);
            mantenimiento.setDescripcion(descripcion);
            mantenimiento.setEstado(estado);
            //metodo guardar
            if (mantenimientoController.guardar(mantenimiento)) {
                JOptionPane.showMessageDialog(null, "¡Mantenimiento Guardado!");

                actualizarStatusEquipo(
                        mantenimiento.getEquipo().getIdEquipo(),
                        "En Mantenimiento"
                );
                //vaciar los campos
                jComboBox_equipos.setSelectedIndex(0);
                txt_codigo.setText("");
                jDateChooser_fecha_inicio.setDate(null);
                jDateChooser_fecha_fin.setDate(null);
                jTextArea_descripcion.setText("");
                jComboBox_estado.setSelectedItem("Activo");

                //Cargar la tabla para actualizar los registros
                this.cargarTablaMantenimientos();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al Guardar!");

            }
        }
    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        String equipo = jComboBox_equipos.getSelectedItem().toString();
        String descripcion = jTextArea_descripcion.getText().trim();
        Date fechaInicioDate = jDateChooser_fecha_inicio.getDate();
        Date fechaFinDate = jDateChooser_fecha_fin.getDate();
        String status = jComboBox_status.getSelectedItem().toString();
        String estado = jComboBox_estado.getSelectedItem().toString();
        //validamos campos vacios
        if (fechaInicioDate == null
                || fechaFinDate == null
                || descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Complete todos los campos!");
        } else {
            Equipo equipoSeleccionado
                    = (Equipo) jComboBox_equipos.getSelectedItem();

            if (equipoSeleccionado == null
                    || equipoSeleccionado.getIdEquipo() == 0) {

                JOptionPane.showMessageDialog(null,
                        "Seleccione un equipo");
                return;
            }

            MantenimientoController mantenimientoController = new MantenimientoController();
            Mantenimiento mantenimiento = new Mantenimiento();
//            Equipo equipoObject = new Equipo();
            LocalDate fechaInicio = fechaInicioDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaFin = fechaFinDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            mantenimiento.setIdMantenimiento(0);
            //--
//            equipoObject.setIdEquipo(equipoObject.getIdEquipo());
//            equipoObject.setNombre(jComboBox_equipos.getSelectedItem().toString());
//            mantenimiento.setEquipo(equipoObject);

            Equipo equipo2
                    = (Equipo) jComboBox_equipos.getSelectedItem();
            equipo2.setStatus(status);

            mantenimiento.setEquipo(equipo2);
            //--
            mantenimiento.setFechaInicio(fechaInicio);
            mantenimiento.setFechaFin(fechaFin);
            mantenimiento.setDescripcion(descripcion);
            mantenimiento.setEstado(estado);
            //metodo guardar
            if (mantenimientoController.actualizar(mantenimiento, idMantenimiento)) {
                JOptionPane.showMessageDialog(null, "¡Mantenimiento Actualizado!");
                //vaciar los campos
                jComboBox_equipos.setSelectedIndex(0);
                txt_codigo.setText("");
                jDateChooser_fecha_inicio.setDate(null);
                jDateChooser_fecha_fin.setDate(null);
                jTextArea_descripcion.setText("");
                jComboBox_estado.setSelectedItem("Activo");

                //Cargar la tabla para actualizar los registros
                this.cargarTablaMantenimientos();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al Actualizar!");

            }
        }

    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jComboBox_equiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_equiposActionPerformed
        Equipo equipo = (Equipo) jComboBox_equipos.getSelectedItem();

        if (equipo != null) {

            txt_codigo.setText(
                    equipo.getCodigo()
                    + " - "
                    + equipo.getMarca());
        }
    }//GEN-LAST:event_jComboBox_equiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoMantenimientoDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoMantenimientoDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoMantenimientoDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoMantenimientoDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoMantenimientoDialogForm dialog = new NuevoMantenimientoDialogForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton_actualizar;
    public static javax.swing.JButton jButton_guardar;
    public static javax.swing.JComboBox jComboBox_equipos;
    public static javax.swing.JComboBox<String> jComboBox_estado;
    public static javax.swing.JComboBox<String> jComboBox_status;
    public static com.toedter.calendar.JDateChooser jDateChooser_fecha_fin;
    public static com.toedter.calendar.JDateChooser jDateChooser_fecha_inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea_descripcion;
    public static javax.swing.JTextField txt_codigo;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo para aplicar los estilos a la tabla
     */
    private void CargarEstilos() {
        // Estilos del encabezado del jtable
        JTableHeader header = InterMantenimiento.jTable_mantenimientos.getTableHeader();
        header.setFont(new Font("Serif", Font.BOLD, 18));  // Fuente negrita para el encabezado
        header.setBackground(Color.WHITE);  // Fondo del encabezado
        header.setForeground(new Color(11, 34, 97));  // Color de Texto del encabezado
        // Cambiar la fuente de la tabla
        InterMantenimiento.jTable_mantenimientos.setFont(new Font("Serif", Font.PLAIN, 20));
        // Cambiar el color de fondo de las celdas seleccionadas
        InterMantenimiento.jTable_mantenimientos.setSelectionBackground(new Color(0, 255, 255));
        // Cambiar el color del texto de las celdas seleccionadas
        InterMantenimiento.jTable_mantenimientos.setSelectionForeground(new Color(30, 119, 37));
        // Cambiar el color de la cuadrícula
        InterMantenimiento.jTable_mantenimientos.setGridColor(Color.BLACK);
        // Ajusta la altura de las filas de la tabla
        InterMantenimiento.jTable_mantenimientos.setRowHeight(30);
    }

    private void cargarTablaMantenimientos() {

        // Crear el controlador 
        MantenimientoController controller = new MantenimientoController();
        ArrayList<Mantenimiento> listaMantenimientos = controller.obtenerMantenimientos();

        // Crear las columnas de la tabla
        String[] columnas = {"ID", "Codigo Equipo", "Equipo", "Fecha Inicio", "Fecha Fin", "Descripcion", "Status", "Estado"};

        // Crear el modelo de la tabla y agregar los datos del ArrayList
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columnas);

        InterMantenimiento.jTable_mantenimientos = new JTable(model);
        InterMantenimiento.jScrollPane1.setViewportView(InterMantenimiento.jTable_mantenimientos);

        this.CargarEstilos();

        // Configurar el ancho de las columnas
        jTable_mantenimientos.getColumnModel().getColumn(0).setPreferredWidth(40);  // ID
        jTable_mantenimientos.getColumnModel().getColumn(1).setPreferredWidth(200); // Codigo Equipo
        jTable_mantenimientos.getColumnModel().getColumn(2).setPreferredWidth(200); // Equipo
        jTable_mantenimientos.getColumnModel().getColumn(3).setPreferredWidth(200); // Fecha Inicio
        jTable_mantenimientos.getColumnModel().getColumn(4).setPreferredWidth(200); // Fecha Fin
        jTable_mantenimientos.getColumnModel().getColumn(5).setPreferredWidth(400); // Descripcion
        jTable_mantenimientos.getColumnModel().getColumn(6).setPreferredWidth(200); // Status
        jTable_mantenimientos.getColumnModel().getColumn(7).setPreferredWidth(200); // estado

        // Llenar el modelo con los datos del ArrayList<Equipo>
        for (Mantenimiento mantenimiento : listaMantenimientos) {
            Object[] fila = {
                mantenimiento.getIdMantenimiento(),
                mantenimiento.getEquipo().getCodigo(),
                mantenimiento.getEquipo().getNombre(),
                mantenimiento.getFechaInicio(),
                mantenimiento.getFechaFin(),
                mantenimiento.getDescripcion(),
                mantenimiento.getEquipo().getStatus(),
                mantenimiento.getEstado()
            };
            model.addRow(fila);
        }

        //evento para obtener campo al cual el usuario da click
        //y obtener la interfaz que mostrara la informacion general
        jTable_mantenimientos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_mantenimientos.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idMantenimiento = (int) model.getValueAt(fila_point, columna_point);
                    controller.enviarDatosAModal(idMantenimiento);//metodo
                }
            }
        });
    }

//    /**
//     * Metodo para cargar las equipos
//     */
//    private void cargarComboEquipos() {
//        java.sql.Connection cn = Conexion.conectar();
//        String sql = "select * from equipo";
//        Statement st;
//        try {
//            st = cn.createStatement();
//            ResultSet rs = st.executeQuery(sql);
//            jComboBox_equipos.removeAllItems();
//            jComboBox_equipos.addItem("Seleccione Equipo:");
//            while (rs.next()) {
//                jComboBox_equipos.addItem(rs.getString("nombre"));
//            }
//        } catch (SQLException e) {
//            System.out.println("Error al cargar los equiposs");
//        }
//    }
    /**
     * Metodo para cargar los equipos
     */
    private void cargarComboEquipos() {

        String sql = "SELECT * FROM equipo";

        try (Connection cn = Conexion.conectar(); Statement st = cn.createStatement(); ResultSet rs = st.executeQuery(sql)) {

            jComboBox_equipos.removeAllItems();

            // Opción "Seleccione Equipo"
            Equipo equipoDefault = new Equipo();
            equipoDefault.setIdEquipo(0);
            equipoDefault.setNombre("Seleccione Equipo:");

            jComboBox_equipos.addItem(equipoDefault);

            while (rs.next()) {

                Equipo equipo = new Equipo();

                equipo.setIdEquipo(rs.getInt("id_equipo"));
                equipo.setCodigo(rs.getString("codigo"));
                equipo.setNombre(rs.getString("nombre"));
                equipo.setMarca(rs.getString("marca"));
                equipo.setModelo(rs.getString("modelo"));
                equipo.setStatus(rs.getString("status"));
                equipo.setEstado(rs.getString("estado"));

                // AQUÍ ESTÁ EL CAMBIO IMPORTANTE
                jComboBox_equipos.addItem(equipo);
            }

        } catch (SQLException e) {
            System.out.println("Error al cargar equipos: "
                    + e.getMessage());
        }
    }

    /**
     * Metodo para obtener id del equipo
     */
//    private int obtenerIdEquipo() {
//        String sql = "select * from equipo where nombre = '" + jComboBox_equipos.getSelectedItem() + "'";
//        Statement st;
//        try {
//            java.sql.Connection cn = Conexion.conectar();
//            st = cn.createStatement();
//            ResultSet rs = st.executeQuery(sql);
//            while (rs.next()) {
//                idEquipo = rs.getInt("id_equipo");
//                codigo = rs.getString("codigo");
//                marca = rs.getString("marca");
//            }
//        } catch (SQLException e) {
//            System.out.println("Error al obener id del equipo");
//        }
//        return idEquipo;
//    }
//    private Equipo obtenerEquipo() {
//
//        Object seleccionado = jComboBox_equipos.getSelectedItem();
//
//        if (seleccionado == null) {
//            return null;
//        }
//
//        Equipo equipo = null;
//        String sql = "SELECT * FROM equipo WHERE nombre = ?";
//        try (Connection cn = Conexion.conectar(); PreparedStatement pst = cn.prepareStatement(sql)) {
//
//            pst.setString(1, jComboBox_equipos.getSelectedItem().toString());
//
//            try (ResultSet rs = pst.executeQuery()) {
//
//                if (rs.next()) {
//
//                    equipo = new Equipo();
//                    equipo.setIdEquipo(rs.getInt("id_equipo"));
//                    equipo.setCodigo(rs.getString("codigo"));
//                    equipo.setNombre(rs.getString("nombre"));
//                    equipo.setMarca(rs.getString("marca"));
//                    equipo.setModelo(rs.getString("modelo"));
//                    equipo.setStatus(rs.getString("status"));
//                    equipo.setEstado(rs.getString("estado"));
//                }
//            }
//
//        } catch (SQLException e) {
//            System.out.println(
//                    "Error al obtener equipo: "
//                    + e.getMessage());
//        }
//        return equipo;
//    }
    //Metodo para hacer un update al status del equipo
    private void actualizarStatusEquipo(int idEquipo, String status) {

        String sql = "UPDATE equipo SET status = ? WHERE id_equipo = ?";

        try (Connection cn = Conexion.conectar(); PreparedStatement pst = cn.prepareStatement(sql)) {

            pst.setString(1, status);
            pst.setInt(2, idEquipo);

            pst.executeUpdate();

        } catch (SQLException e) {
            System.out.println(
                    "Error al actualizar status del equipo: "
                    + e.getMessage());
        }
    }
}
