package vista;

import conexion.Conexion;
import controlador.CategoriaController;
import controlador.UsuarioController;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import modelo.Categoria;
import static vista.InterCategoria.jTable_categorias;

/**
 *
 * @author Grupo 3
 */
public class NuevaCategoriaDialogForm extends javax.swing.JDialog {

    /**
     * Creates new form NuevaCategoriaDialogForm
     */
    private static int idCategoria = InterCategoria.idCategoria;

    public NuevaCategoriaDialogForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Categoria");
        setLayout(null);
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        // Crear un borde para solo la parte inferior
        Border bottomBorder = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK);

        // Aplicar el borde solo al JTextField
        txt_nombre.setBorder(bottomBorder);
        txt_descripcion.setBorder(bottomBorder);
        jComboBox_estado.setBackground(Color.LIGHT_GRAY); // Fondo del JComboBox

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        jComboBox_estado = new javax.swing.JComboBox<>();
        jButton_guardar = new javax.swing.JButton();
        jButton_actualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Nombres:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Descripción:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Estado:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txt_nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 550, 30));

        txt_descripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 550, 30));

        jComboBox_estado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jPanel1.add(jComboBox_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 250, 30));

        jButton_guardar.setBackground(new java.awt.Color(0, 102, 255));
        jButton_guardar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        jButton_guardar.setText("GUARDAR");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 200, 40));

        jButton_actualizar.setBackground(new java.awt.Color(0, 204, 102));
        jButton_actualizar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        jButton_actualizar.setText("ACTUALIZAR");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 600, 530));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS DE LA CATEGORIA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 10, 600, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed

        String nombres = txt_nombre.getText().trim();
        String descripcion = txt_descripcion.getText().trim();
        String estado = jComboBox_estado.getSelectedItem().toString();
        //validamos campos vacios
        if (nombres.isEmpty() || descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Complete todos los campos!");
        } else {
            CategoriaController categoriaController = new CategoriaController();

            Categoria categoria = new Categoria();
            categoria.setIdCategoria(0);
            categoria.setNombre(nombres);
            categoria.setDescripcion(descripcion);
            categoria.setEstado(estado);
            //metodo guardar
            if (categoriaController.guardar(categoria)) {
                JOptionPane.showMessageDialog(null, "¡Categoria Guardada!");
                //vaciar los campos
                txt_nombre.setText("");
                txt_descripcion.setText("");
                jComboBox_estado.setSelectedItem("Activo");

                //Cargar la tabla para actualizar los registros
                this.cargarTablaCategorias();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al Guardar!");

            }
        }
    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed

        String nombres = txt_nombre.getText().trim();
        String descripcion = txt_descripcion.getText().trim();
        String estado = jComboBox_estado.getSelectedItem().toString();
        //validamos campos vacios
        if (nombres.isEmpty() || descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Complete todos los campos!");
        } else {
            CategoriaController categoriaController = new CategoriaController();

            Categoria categoria = new Categoria();
            categoria.setIdCategoria(0);
            categoria.setNombre(nombres);
            categoria.setDescripcion(descripcion);
            categoria.setEstado(estado);
            //metodo actualizar
            if (categoriaController.actualizar(categoria, idCategoria)) {
                JOptionPane.showMessageDialog(null, "¡Categoria Actualizada!");
                //vaciar los campos
                txt_nombre.setText("");
                txt_descripcion.setText("");
                jComboBox_estado.setSelectedItem("Activo");

                //Cargar la tabla para actualizar los registros
                this.cargarTablaCategorias();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al Actualizar!");

            }
        }

    }//GEN-LAST:event_jButton_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaCategoriaDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaCategoriaDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaCategoriaDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaCategoriaDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevaCategoriaDialogForm dialog = new NuevaCategoriaDialogForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton_actualizar;
    public static javax.swing.JButton jButton_guardar;
    public static javax.swing.JComboBox<String> jComboBox_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField txt_descripcion;
    public static javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo para aplicar los estilos a la tabla
     */
    private void CargarEstilos() {
        // Estilos del encabezado del jtable
        JTableHeader header = InterCategoria.jTable_categorias.getTableHeader();
        header.setFont(new Font("Serif", Font.BOLD, 18));  // Fuente negrita para el encabezado
        header.setBackground(Color.WHITE);  // Fondo del encabezado
        header.setForeground(new Color(11, 34, 97));  // Color de Texto del encabezado
        // Cambiar la fuente de la tabla
        InterCategoria.jTable_categorias.setFont(new Font("Serif", Font.PLAIN, 20));
        // Cambiar el color de fondo de las celdas seleccionadas
        InterCategoria.jTable_categorias.setSelectionBackground(new Color(0, 255, 255));
        // Cambiar el color del texto de las celdas seleccionadas
        InterCategoria.jTable_categorias.setSelectionForeground(new Color(30, 119, 37));
        // Cambiar el color de la cuadrícula
        InterCategoria.jTable_categorias.setGridColor(Color.BLACK);
        // Ajusta la altura de las filas de la tabla
        InterCategoria.jTable_categorias.setRowHeight(30);
    }

    private void cargarTablaCategorias() {

        // Crear el controlador y obtener los estudiantes
        CategoriaController controller = new CategoriaController();
        ArrayList<Categoria> listaCategorias = controller.obtenerCategorias();

        // Crear las columnas de la tabla
        String[] columnas = {"ID", "Nombres", "Descripcion", "Estado"};

        // Crear el modelo de la tabla y agregar los datos del ArrayList
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columnas);

        InterCategoria.jTable_categorias = new JTable(model);
        InterCategoria.jScrollPane1.setViewportView(InterCategoria.jTable_categorias);

        this.CargarEstilos();

        // Configurar el ancho de las columnas
        jTable_categorias.getColumnModel().getColumn(0).setPreferredWidth(40);  // ID
        jTable_categorias.getColumnModel().getColumn(1).setPreferredWidth(350); // Nombres
        jTable_categorias.getColumnModel().getColumn(2).setPreferredWidth(600); // Descripcion
        jTable_categorias.getColumnModel().getColumn(3).setPreferredWidth(250); // Estado

        // Llenar el modelo con los datos del ArrayList<Usuarios>
        for (Categoria categoria : listaCategorias) {
            Object[] fila = {
                categoria.getIdCategoria(),
                categoria.getNombre(),
                categoria.getDescripcion(),
                categoria.getEstado()
            };
            model.addRow(fila);
        }

        //evento para obtener campo al cual el usuario da click
        //y obtener la interfaz que mostrara la informacion general
        jTable_categorias.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_categorias.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idCategoria = (int) model.getValueAt(fila_point, columna_point);
                    controller.enviarDatosAModal(idCategoria);//metodo
                }
            }
        });
    }
}
