package vista;

import conexion.Conexion;
import controlador.UsuarioController;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import modelo.TipoUsuario;
import modelo.Usuario;
import static vista.InterUsuario.jTable_usuarios;

/**
 *
 * @author Grupo 3
 */
public class NuevoUsuarioDialogForm extends javax.swing.JDialog {

    /**
     * Creates new form NuevoEstudianteDialogForm
     */
    private static int idUsuario = InterUsuario.idUsuario;
    private int idTipoUsuario = 0;

    public NuevoUsuarioDialogForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Nuevo Estudiante");
        setLayout(null);
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        // Crear un borde para solo la parte inferior
        Border bottomBorder = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK);

        // Aplicar el borde solo al JTextField
        txt_nombres.setBorder(bottomBorder);
        txt_apellidos.setBorder(bottomBorder);
        txt_correo.setBorder(bottomBorder);
        txt_clave.setBorder(bottomBorder);
        jComboBox_tipo_usuario.setBackground(Color.LIGHT_GRAY); // Fondo del JComboBox
        jComboBox_estado.setBackground(Color.LIGHT_GRAY); // Fondo del JComboBox

        //cargar metodos
        cargarComboTipoUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_clave = new javax.swing.JTextField();
        jComboBox_estado = new javax.swing.JComboBox<>();
        jButton_guardar = new javax.swing.JButton();
        jButton_actualizar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_tipo_usuario = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Nombres:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Apellidos:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Correo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Clave:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Estado:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        txt_apellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 250, 30));

        txt_nombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, 30));

        txt_correo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 250, 30));

        txt_clave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 250, 30));

        jComboBox_estado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jPanel1.add(jComboBox_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 250, 30));

        jButton_guardar.setBackground(new java.awt.Color(0, 102, 255));
        jButton_guardar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        jButton_guardar.setText("GUARDAR");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 200, 40));

        jButton_actualizar.setBackground(new java.awt.Color(0, 204, 102));
        jButton_actualizar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        jButton_actualizar.setText("ACTUALIZAR");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 200, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Tipo Usuario:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jComboBox_tipo_usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_tipo_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tipo Usuario:" }));
        jPanel1.add(jComboBox_tipo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 250, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 600, 530));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS DEL USUARIO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 10, 600, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed

        String tipo_usuario = jComboBox_tipo_usuario.getSelectedItem().toString();
        String nombres = txt_nombres.getText().trim();
        String apellidos = txt_apellidos.getText().trim();
        String correo = txt_correo.getText().trim();
        String clave = txt_clave.getText().trim();
        String estado = jComboBox_estado.getSelectedItem().toString();
        //validamos campos vacios
        if (nombres.isEmpty() || apellidos.isEmpty() || correo.isEmpty()
                || clave.isEmpty() || tipo_usuario.equals("Seleccione Tipo Usuario:")) {
            JOptionPane.showMessageDialog(null, "¡Complete todos los campos!");
        } else {
            UsuarioController usuarioController = new UsuarioController();

            Usuario usuario = new Usuario();
            TipoUsuario tipo = new TipoUsuario();

            usuario.setIdUsuario(0);
//            usuario.setIdTipoUsuario(1);
            tipo.setIdTipoUsuario(obtenerIdTipoUsuario());
            usuario.setNombres(nombres);
            usuario.setApellidos(apellidos);
            usuario.setCorreo(correo);
            usuario.setClave(clave);
            usuario.setEstado(estado);
            //metodo guardar
            if (usuarioController.guardar(usuario, tipo)) {
                JOptionPane.showMessageDialog(null, "¡Usuario Guardado!");
                //vaciar los campos
                txt_nombres.setText("");
                txt_apellidos.setText("");
                txt_correo.setText("");
                txt_clave.setText("");
                jComboBox_estado.setSelectedItem("Activo");
                jComboBox_estado.setSelectedItem("Seleccione Tipo Usuario:");

                //Cargar la tabla para actualizar los registros
                this.cargarTablaUsuarios();
//                        System.out.println("Helloooo!!!!!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al Guardar!");

            }
        }
    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed

        String tipo_usuario = jComboBox_tipo_usuario.getSelectedItem().toString();
        String nombres = txt_nombres.getText().trim();
        String apellidos = txt_apellidos.getText().trim();
        String correo = txt_correo.getText().trim();
        String clave = txt_clave.getText().trim();
        String estado = jComboBox_estado.getSelectedItem().toString();
        //validamos campos vacios
        if (nombres.isEmpty() || apellidos.isEmpty() || correo.isEmpty()
                || clave.isEmpty() || tipo_usuario.equals("Seleccione Tipo Usuario:")) {
            JOptionPane.showMessageDialog(null, "¡Complete todos los campos!");
        } else {
            UsuarioController usuarioController = new UsuarioController();

            Usuario usuario = new Usuario();
            TipoUsuario tipo = new TipoUsuario();

            usuario.setIdUsuario(0);
//            usuario.setIdTipoUsuario(1);
            tipo.setIdTipoUsuario(obtenerIdTipoUsuario());
            usuario.setNombres(nombres);
            usuario.setApellidos(apellidos);
            usuario.setCorreo(correo);
            usuario.setClave(clave);
            usuario.setEstado(estado);
            //metodo guardar
            if (usuarioController.actualizar(usuario, tipo, idUsuario)) {
                JOptionPane.showMessageDialog(null, "¡Usuario Actualizado!");
                //vaciar los campos
                txt_nombres.setText("");
                txt_apellidos.setText("");
                txt_correo.setText("");
                txt_clave.setText("");
                jComboBox_estado.setSelectedItem("Activo");
                jComboBox_estado.setSelectedItem("Seleccione Tipo Usuario:");

                //Cargar la tabla para actualizar los registros
                this.cargarTablaUsuarios();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al Actualizar!");
            }
        }
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuarioDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuarioDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuarioDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuarioDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoUsuarioDialogForm dialog = new NuevoUsuarioDialogForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton_actualizar;
    public static javax.swing.JButton jButton_guardar;
    public static javax.swing.JComboBox<String> jComboBox_estado;
    public static javax.swing.JComboBox<String> jComboBox_tipo_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField txt_apellidos;
    public static javax.swing.JTextField txt_clave;
    public static javax.swing.JTextField txt_correo;
    public static javax.swing.JTextField txt_nombres;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo para aplicar los estilos a la tabla
     */
    private void CargarEstilos() {
        // Estilos del encabezado del jtable
        JTableHeader header = InterUsuario.jTable_usuarios.getTableHeader();
        header.setFont(new Font("Serif", Font.BOLD, 18));  // Fuente negrita para el encabezado
        header.setBackground(Color.WHITE);  // Fondo del encabezado
        header.setForeground(new Color(11, 34, 97));  // Color de Texto del encabezado
        // Cambiar la fuente de la tabla
        InterUsuario.jTable_usuarios.setFont(new Font("Serif", Font.PLAIN, 20));
        // Cambiar el color de fondo de las celdas seleccionadas
        InterUsuario.jTable_usuarios.setSelectionBackground(new Color(0, 255, 255));
        // Cambiar el color del texto de las celdas seleccionadas
        InterUsuario.jTable_usuarios.setSelectionForeground(new Color(30, 119, 37));
        // Cambiar el color de la cuadrícula
        InterUsuario.jTable_usuarios.setGridColor(Color.BLACK);
        // Ajusta la altura de las filas de la tabla
        InterUsuario.jTable_usuarios.setRowHeight(30);
    }

    private void cargarTablaUsuarios() {

        // Crear el controlador y obtener los estudiantes
        UsuarioController controller = new UsuarioController();
        ArrayList<Usuario> listaUsuarios = controller.obtenerUsuarios();

        // Crear las columnas de la tabla
        String[] columnas = {"ID", "Tipo Usuario", "Nombres", "Correo", "Clave", "Estado"};

        // Crear el modelo de la tabla y agregar los datos del ArrayList
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columnas);

        InterUsuario.jTable_usuarios = new JTable(model);
        InterUsuario.jScrollPane1.setViewportView(InterUsuario.jTable_usuarios);

        this.CargarEstilos();

        // Configurar el ancho de las columnas
        jTable_usuarios.getColumnModel().getColumn(0).setPreferredWidth(40);  // ID
        jTable_usuarios.getColumnModel().getColumn(1).setPreferredWidth(300); // Tipo de Usuario
        jTable_usuarios.getColumnModel().getColumn(2).setPreferredWidth(350); // Nombres
        jTable_usuarios.getColumnModel().getColumn(3).setPreferredWidth(300); // Correo
        jTable_usuarios.getColumnModel().getColumn(4).setPreferredWidth(200); // Clave
        jTable_usuarios.getColumnModel().getColumn(5).setPreferredWidth(150); // Estado

        // Llenar el modelo con los datos del ArrayList<Usuarios>
        for (Usuario usuario : listaUsuarios) {
            Object[] fila = {
                usuario.getIdUsuario(),
                usuario.getTipo_usuario().getDescripcion(),
                usuario.getNombres() + " " + usuario.getApellidos(),
                usuario.getCorreo(),
                usuario.getClave(),
                usuario.getEstado()
            };
            model.addRow(fila);
        }

        //evento para obtener campo al cual el usuario da click
        //y obtener la interfaz que mostrara la informacion general
        jTable_usuarios.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_usuarios.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idUsuario = (int) model.getValueAt(fila_point, columna_point);
                    controller.enviarDatosAModal(idUsuario);//metodo
                }
            }
        });
    }

    /**
     * Metodo para cargar los tipos de usuarios
     */
    private void cargarComboTipoUsuario() {
        java.sql.Connection cn = Conexion.conectar();
        String sql = "select * from tipo_usuario";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_tipo_usuario.removeAllItems();
            jComboBox_tipo_usuario.addItem("Seleccione Tipo Usuario:");
            while (rs.next()) {
                jComboBox_tipo_usuario.addItem(rs.getString("descripcion"));
            }
        } catch (SQLException e) {
            System.out.println("Error al cargar tipos de usuarios");
        }
    }

    /**
     * Metodo para obtener id del tipo de usuario
     */
    private int obtenerIdTipoUsuario() {
        String sql = "select * from tipo_usuario where descripcion = '" + jComboBox_tipo_usuario.getSelectedItem() + "'";
        Statement st;
        try {
            java.sql.Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                idTipoUsuario = rs.getInt("id_tipo_usuario");
            }
        } catch (SQLException e) {
            System.out.println("Error al obener id tipo de usuario");
        }
        return idTipoUsuario;
    }

}
